# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_text', models.CharField(max_length=200)),
                ('name_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_date', models.DateTimeField(verbose_name='date')),
                ('close_float', models.FloatField(verbose_name='close price')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyMomentumApp.Instrument')),
            ],
        ),
    ]
