# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyMomentumApp', '0002_auto_20170512_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instrument',
            name='price',
        ),
        migrations.AddField(
            model_name='price',
            name='instrument',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyMomentumApp.Instrument'),
        ),
    ]
